version: '3.8'

services:
  app:
    build: .
    container_name: music_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/wait-for-it.sh", "music_db:5432", "--", "./musicinstruments"]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qweqwe123
      - DB_NAME=musicshop
    restart: always

  db:
    image: postgres:15
    container_name: music_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweqwe123
      POSTGRES_DB: musicshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
